version: "3.7"
services:
  deepstack:
    image: deepquestai/deepstack:latest
    restart: unless-stopped
    container_name: deepstack
    ports:
      - "80:5000"
    environment:
      - VISION-DETECTION=True
    volumes:
      - ./deepstack:/datastore